export const leaderboard_dummy_data = [
    
        {rank: 1, discord_id: 'dj1nnn.', points: 1631, tier: 'Red Wolf & Puppy'},
        {rank: 2, discord_id: 'jlji', points: 1105, tier: 'Red Wolf & Puppy'},
        {rank: 3, discord_id: 'nurstar', points: 928, tier: 'Red Wolf & Puppy'},
        {rank: 4, discord_id: '0xredman', points: 757, tier: 'Puppy'},
        {rank: 5, discord_id: 'vladstarkdegenz', points: 724, tier: 'Puppy'},
        {rank: 6, discord_id: 'fabiocatalao', points: 678, tier: 'Puppy'},
        {rank: 7, discord_id: 'ollie.eth', points: 677, tier: 'Puppy'},
        {rank: 8, discord_id: 'starkythedoggo', points: 589, tier: 'Puppy'},
        {rank: 9, discord_id: 'xerantia', points: 576, tier: 'Puppy'},
        {rank: 10, discord_id: 'calcutator', points: 555, tier: 'Puppy'},
        {rank: 11, discord_id: 'thann1995', points: 520, tier: 'Puppy'},
        {rank: 12, discord_id: 'samrendra.singh', points: 519, tier: 'Puppy'},
        {rank: 13, discord_id: 'Bert of B', points: 512, tier: 'Puppy'},
        {rank: 14, discord_id: 'hdai58', points: 503, tier: 'Puppy'},
        {rank: 15, discord_id: 'lordcumberlord', points: 458, tier: 'Puppy'},
        {rank: 16, discord_id: 'cheelax', points: 443, tier: 'Puppy'},
        {rank: 17, discord_id: 'apixtwts', points: 417, tier: 'Puppy'},
        {rank: 18, discord_id: 'megumii.eth', points: 410, tier: 'Puppy'},
        {rank: 19, discord_id: 'paulemmanuelng', points: 376, tier: 'Puppy'},
        {rank: 20, discord_id: 'nadai02010', points: 363, tier: 'Puppy'},
        {rank: 21, discord_id: 'femiyoghurt', points: 360, tier: 'Puppy'},
        {rank: 22, discord_id: '0xandee', points: 350, tier: 'Puppy'},
        {rank: 23, discord_id: '.bole007', points: 344, tier: 'Puppy'},
        {rank: 24, discord_id: 'phil26', points: 341, tier: 'Puppy'},
        {rank: 25, discord_id: 'louthing', points: 341, tier: 'Puppy'},
        {rank: 26, discord_id: '.sdav', points: 335, tier: 'Puppy'},
        {rank: 27, discord_id: 'gabecartridge', points: 322, tier: 'Puppy'},
        {rank: 28, discord_id: 'gtf.eth_78846', points: 294, tier: 'Puppy'},
        {rank: 29, discord_id: 'danielbeja', points: 292, tier: 'Puppy'},
        {rank: 30, discord_id: 'crypto.stark', points: 287, tier: 'Puppy'},
        {rank: 31, discord_id: 'lordsquiddy', points: 268, tier: 'Puppy'},
        {rank: 32, discord_id: 'buremo', points: 264, tier: 'Puppy'},
        {rank: 33, discord_id: 'nggax100', points: 251, tier: 'Puppy'},
        {rank: 34, discord_id: 'gogibear', points: 248, tier: 'Puppy'},
        {rank: 35, discord_id: 'mazelecta', points: 232, tier: 'Puppy'},
        {rank: 36, discord_id: 'kkai_kaydd', points: 221, tier: 'Puppy'},
        {rank: 37, discord_id: 'defisaintkromcontributor', points: 219, tier: 'Puppy'},
        {rank: 38, discord_id: 'tashabullishovna', points: 209, tier: 'Puppy'},
        {rank: 39, discord_id: 'avader_', points: 205, tier: 'Puppy'},
        {rank: 40, discord_id: 'tekkac', points: 186, tier: 'Puppy'},
        {rank: 41, discord_id: 'senku_stark', points: 177, tier: 'Puppy'},
        {rank: 42, discord_id: 'hamd1st', points: 173, tier: 'Puppy'},
        {rank: 43, discord_id: 'alex_pashevich', points: 172, tier: 'Puppy'},
        {rank: 44, discord_id: '60_061', points: 167, tier: 'Puppy'},
        {rank: 45, discord_id: 'hugo0x', points: 164, tier: 'Puppy'},
        {rank: 46, discord_id: 'karlostoteles', points: 162, tier: 'Puppy'},
        {rank: 47, discord_id: 'yoyo.stark', points: 160, tier: 'Puppy'},
        {rank: 48, discord_id: '! Layer2ID', points: 147, tier: 'Puppy'},
        {rank: 49, discord_id: 'handlerr', points: 147, tier: 'Puppy'},
        {rank: 50, discord_id: 'rakkiotoko', points: 145, tier: 'Puppy'},
        {rank: 51, discord_id: 'muguika', points: 143, tier: 'Puppy'},
        {rank: 52, discord_id: 'Stark Hub Brasil', points: 137, tier: 'Puppy'},
        {rank: 53, discord_id: '2cosmonautes', points: 129, tier: 'Puppy'},
        {rank: 54, discord_id: 'rektor', points: 126, tier: 'Puppy'},
        {rank: 55, discord_id: 'starknetes', points: 126, tier: 'Puppy'},
        {rank: 56, discord_id: 'vickish111', points: 119, tier: 'Puppy'},
        {rank: 57, discord_id: 'juno0601', points: 116, tier: 'Puppy'},
        {rank: 58, discord_id: 'agrozold', points: 109, tier: 'Puppy'},
        {rank: 59, discord_id: 'jimmy2jacket', points: 109, tier: 'Puppy'},
        {rank: 60, discord_id: 'im_dave_', points: 108, tier: 'Puppy'},
        {rank: 61, discord_id: 'ihor0732', points: 107, tier: 'Puppy'},
        {rank: 62, discord_id: 'hova2418', points: 104, tier: 'Puppy'},
        {rank: 63, discord_id: 'soycripto', points: 99, tier: 'Puppy'},
        {rank: 64, discord_id: 'ainullindale', points: 98, tier: 'Puppy'},
        {rank: 65, discord_id: 'rroydd', points: 97, tier: 'Puppy'},
        {rank: 66, discord_id: 'no record', points: 95, tier: 'Puppy'},
        {rank: 67, discord_id: 'gaetbout', points: 91, tier: 'Puppy'},
        {rank: 68, discord_id: 'dianeu5380', points: 90, tier: 'Puppy'},
        {rank: 69, discord_id: 'behtin', points: 79, tier: 'Puppy'},
        {rank: 70, discord_id: 'maxlion_astro', points: 69, tier: 'Puppy'},
        {rank: 71, discord_id: 'evans007', points: 69, tier: 'Puppy'},
        {rank: 72, discord_id: 'maxv001', points: 68, tier: 'Puppy'},
        {rank: 73, discord_id: 'orgazmio', points: 63, tier: 'Puppy'},
        {rank: 74, discord_id: 'shelleymae', points: 63, tier: 'Puppy'},
        {rank: 75, discord_id: 'cryptoricot.eth', points: 60, tier: 'Puppy'},
        {rank: 76, discord_id: 'kechei_', points: 58, tier: 'Puppy'},
        {rank: 77, discord_id: 'karub.eth', points: 56, tier: 'Puppy'},
        {rank: 78, discord_id: 'raizo007.', points: 56, tier: 'Puppy'},
        {rank: 79, discord_id: 'leogravina', points: 53, tier: 'Puppy'},
        {rank: 80, discord_id: 'onbodem', points: 50, tier: 'Puppy'},
        {rank: 81, discord_id: 'jaimes49265', points: 50, tier: 'Puppy'},
        {rank: 82, discord_id: 'hessish', points: 50, tier: 'Puppy'},
        {rank: 83, discord_id: 'leoyoung', points: 49, tier: 'Puppy'},
        {rank: 84, discord_id: 'kellou4491', points: 48, tier: 'Puppy'},
        {rank: 85, discord_id: 'antoine_argent.xyz', points: 46, tier: 'Puppy'},
        {rank: 86, discord_id: 'saurabhshetty', points: 45, tier: 'Puppy'},
        {rank: 87, discord_id: 'naveenzkx', points: 44, tier: 'Puppy'},
        {rank: 88, discord_id: 'deliamayami', points: 43, tier: 'Puppy'},
        {rank: 89, discord_id: 'yura4654', points: 43, tier: 'Puppy'},
        {rank: 90, discord_id: 'delta3a', points: 42, tier: 'Puppy'},
        {rank: 91, discord_id: 'coingeener', points: 41, tier: 'Puppy'},
        {rank: 92, discord_id: '0xasten', points: 41, tier: 'Puppy'},
        {rank: 93, discord_id: 'recipromancer', points: 40, tier: 'Puppy'},
        {rank: 94, discord_id: 'milyu', points: 39, tier: 'Puppy'},
        {rank: 95, discord_id: 'immanuel_olivia', points: 37, tier: 'Puppy'},
        {rank: 96, discord_id: 'arturobx', points: 34, tier: 'Puppy'},
        {rank: 97, discord_id: 'aleksander100', points: 34, tier: 'Puppy'},
        {rank: 98, discord_id: 'richard120', points: 33, tier: 'Puppy'},
        {rank: 99, discord_id: 'web3gurung', points: 33, tier: 'Puppy'},
        {rank: 100, discord_id: 'tomaszcrypto730', points: 31, tier: 'Puppy'},
        {rank: 101, discord_id: 'jejom43', points: 30, tier: 'Puppy'},
        {rank: 102, discord_id: 'micka_18', points: 30, tier: 'Puppy'},
        {rank: 103, discord_id: 'jc3910', points: 29, tier: 'Puppy'},
        {rank: 104, discord_id: 'katsuyusama', points: 29, tier: 'Puppy'},
        {rank: 105, discord_id: 'scriptmoney', points: 28, tier: 'Puppy'},
        {rank: 106, discord_id: 'snowliii', points: 28, tier: 'Puppy'},
        {rank: 107, discord_id: 'bossprince', points: 28, tier: 'Puppy'},
        {rank: 108, discord_id: 'maksym5868', points: 27, tier: 'Puppy'},
        {rank: 109, discord_id: 'khairallah', points: 24, tier: 'Puppy'},
        {rank: 110, discord_id: 'no record', points: 24, tier: 'Puppy'},
        {rank: 111, discord_id: 'ocheesther', points: 24, tier: 'Puppy'},
        {rank: 112, discord_id: 'mataleone', points: 24, tier: 'Puppy'},
        {rank: 113, discord_id: 'paskon4ick', points: 23, tier: 'Puppy'},
        {rank: 114, discord_id: 'IamEnergyI', points: 23, tier: 'Puppy'},
        {rank: 115, discord_id: 'mrbabs', points: 22, tier: 'Puppy'},
        {rank: 116, discord_id: 'hope.gg', points: 21, tier: 'Puppy'},
        {rank: 117, discord_id: 'ryand0423', points: 21, tier: 'Puppy'},
        {rank: 118, discord_id: 'crypto_guy', points: 21, tier: 'Puppy'},
        {rank: 119, discord_id: 'osguridascripto', points: 20, tier: 'Puppy'},
        {rank: 120, discord_id: 'amarachiugwu', points: 19, tier: 'Puppy'},
        {rank: 121, discord_id: 'nick_you_', points: 19, tier: 'Puppy'},
        {rank: 122, discord_id: 'julierb06', points: 17, tier: 'Puppy'},
        {rank: 123, discord_id: '0xteejey', points: 17, tier: 'Puppy'},
        {rank: 124, discord_id: 'kroko_bams', points: 17, tier: 'Puppy'},
        {rank: 125, discord_id: 'HOSSEIN', points: 17, tier: 'Puppy'},
        {rank: 126, discord_id: 'kawaka_a', points: 14, tier: 'Puppy'},
        {rank: 127, discord_id: 'syphilis6688', points: 14, tier: 'Puppy'},
        {rank: 128, discord_id: 'iwantanode', points: 14, tier: 'Puppy'},
        {rank: 129, discord_id: '0xweb3dev', points: 13, tier: 'Puppy'},
        {rank: 130, discord_id: 'edik_fnd', points: 13, tier: 'Puppy'},
        {rank: 131, discord_id: 'julio4', points: 13, tier: 'Puppy'},
    {rank: 132, discord_id: 'kakoozavian.', points: 12, tier: 'Puppy'},
    {rank: 133, discord_id: 'moqiao', points: 12, tier: 'Puppy'},
    {rank: 134, discord_id: 'multicat', points: 12, tier: 'Puppy'},
    {rank: 135, discord_id: 'satyambnsal', points: 11, tier: 'Puppy'},
    {rank: 136, discord_id: 'Reg_Horace', points: 11, tier: 'Puppy'},
    {rank: 137, discord_id: 'only1temmy.', points: 11, tier: 'Puppy'},
    {rank: 138, discord_id: '0xshora', points: 11, tier: 'Puppy'},
    {rank: 139, discord_id: 'khemmie_ray', points: 10, tier: 'Puppy'},
    {rank: 140, discord_id: 'liamthedawn', points: 10, tier: 'Puppy'},
    {rank: 141, discord_id: 'Anıl', points: 9, tier: 'Puppy'},
    {rank: 142, discord_id: 'bodik4612', points: 9, tier: 'Puppy'},
    {rank: 143, discord_id: 'heikel', points: 8, tier: 'Puppy'},
    {rank: 144, discord_id: 'mservais', points: 8, tier: 'Puppy'},
    {rank: 145, discord_id: 'provablemat', points: 8, tier: 'Puppy'},
    {rank: 146, discord_id: 'nandyba', points: 7, tier: 'Puppy'},
    {rank: 147, discord_id: '0xgiwook', points: 6, tier: 'Puppy'},
    {rank: 148, discord_id: 'juliencoppola', points: 6, tier: 'Puppy'},
    {rank: 149, discord_id: '0xnestor', points: 5, tier: 'Puppy'},
    {rank: 150, discord_id: 'wong_ssh', points: 5, tier: 'Puppy'},
    {rank: 151, discord_id: 'flavinho0726', points: 5, tier: 'Puppy'},
    {rank: 152, discord_id: 'tradesgiving', points: 4, tier: 'Puppy'},
    {rank: 153, discord_id: 'tomynocker', points: 3, tier: 'Puppy'},
    {rank: 154, discord_id: 'web3ocean', points: 3, tier: 'Puppy'},
    {rank: 155, discord_id: 'simpletox', points: 3, tier: 'Puppy'},
    {rank: 156, discord_id: 'milka69', points: 2, tier: 'Puppy'},
    {rank: 157, discord_id: 'aak0x', points: 2, tier: 'Puppy'},
    {rank: 158, discord_id: 'hashvalue', points: 2, tier: 'Puppy'},
    {rank: 159, discord_id: 'scissors_fb', points: 1, tier: 'Puppy'},
    {rank: 160, discord_id: 'alphab1', points: 0, tier: 'Puppy'},
    {rank: 161, discord_id: 'emmaglorypraise', points: 0, tier: 'Puppy'},
    {rank: 162, discord_id: 'ViktorDefi', points: 0, tier: 'Puppy'},
    {rank: 163, discord_id: 'DeFiTeddy2020', points: 0, tier: 'Puppy'},
    {rank: 164, discord_id: 'darklord2015', points: 0, tier: 'Puppy'},
    {rank: 165, discord_id: 'collins6646', points: 0, tier: 'Puppy'},
    {rank: 166, discord_id: 'remedcu', points: 0, tier: 'Puppy'},
    {rank: 167, discord_id: 'shuaiguo', points: 0, tier: 'Puppy'},
    {rank: 168, discord_id: '0xEvix', points: 0, tier: 'Puppy'},
    {rank: 169, discord_id: '0xzenitsu', points: 0, tier: 'Puppy'},
    {rank: 170, discord_id: 'nilaaa6501', points: 0, tier: 'Puppy'},
    {rank: 171, discord_id: 'alphainsiders', points: 0, tier: 'Puppy'},
    {rank: 172, discord_id: 'gnarly_narwhal', points: 0, tier: 'Puppy'},
    {rank: 173, discord_id: 'bleezysmart', points: 0, tier: 'Puppy'},
    {rank: 174, discord_id: 'kayzee1247', points: 0, tier: 'Puppy'},
    {rank: 175, discord_id: 'laoyang33', points: 0, tier: 'Puppy'},
]

export const about_table_data = [
    {tier: 'Puppy', points: 330, reward: '$688'},
    {tier: 'Red Wolf', points: 990, reward: '$1,376'},
    {tier: 'Arctic Wolf', points: 1980, reward: '$2,063'},
    {tier: 'Gray Wolf', points: 3300, reward: '$2,751'},
    {tier: 'Celestial Wolf', points: 4950, reward: '$3,439'},
    {tier: 'Fire Wolf', points: 6930, reward: '$4,127'},
    {tier: 'Shadow Wolf', points: 9240, reward: '$4,815'},
    {tier: 'Ice Wolf', points: 11880, reward: '$5,502'},
    {tier: 'Thunder Wolf', points: 14850, reward: '$6,190'},
    {tier: 'Warg', points: 18150, reward: '$6,878'},
    {tier: 'Werewolf', points: 21780, reward: '$7,566'},
    {tier: 'Fenrir', points: 25740, reward: '$8,253'},
    {tier: 'Dire Wolf', points: 30030, reward: '$8,941'},
]
