export const leaderboard_dummy_data = [
    {rank: 1, discord_id: 'dj1nnn.', points: 1631, tier: 'Red Wolf & Puppy'},
    {rank: 2, discord_id: 'jlji', points: 1105, tier: 'Red Wolf & Puppy'},
    {rank: 3, discord_id: 'nurstar', points: 928, tier: 'Red Wolf & Puppy'},
    {rank: 4, discord_id: '0xredman', points: 757, tier: 'Puppy'},
    {rank: 5, discord_id: 'vladstarkdegenz', points: 724, tier: 'Puppy'},
    {rank: 6, discord_id: 'fabiocatalao', points: 678, tier: 'Puppy'},
    {rank: 7, discord_id: 'ollie.eth', points: 677, tier: 'Puppy'},
    {rank: 8, discord_id: 'starkythedoggo', points: 589, tier: 'Puppy'},
    {rank: 9, discord_id: 'xerantia', points: 576, tier: 'Puppy'},
    {rank: 10, discord_id: 'calcutator', points: 555, tier: 'Puppy'},
    {rank: 11, discord_id: 'thann199', points: 520, tier: 'Puppy'},
    {rank: 12, discord_id: 'samrendra.singh', points: 519, tier: 'Puppy'},
    {rank: 13, discord_id: 'Bert of B', points: 512, tier: 'Puppy'},
    {rank: 14, discord_id: 'hdai58', points: 503, tier: 'Puppy'},
    {rank: 15, discord_id: 'lordcumberlord', points: 458, tier: 'Puppy'},
    {rank: 16, discord_id: 'cheelax', points: 443, tier: 'Puppy'},
    {rank: 17, discord_id: 'apixtwts', points: 417, tier: 'Puppy'},
    {rank: 18, discord_id: 'megumii.eth', points: 410, tier: 'Puppy'},
    {rank: 19, discord_id: 'paulemmanuelng', points: 376, tier: 'Puppy'},
    {rank: 20, discord_id: 'nadai02010', points: 363, tier: 'Puppy'},
    {rank: 21, discord_id: 'femiyoghurt', points: 360, tier: 'Puppy'},
    {rank: 22, discord_id: '0xandee', points: 350, tier: 'Puppy'},
    {rank: 23, discord_id: '.bole007', points: 344, tier: 'Puppy'},
    {rank: 24, discord_id: 'phil26', points: 341, tier: 'Puppy'},
    {rank: 25, discord_id: 'louthing', points: 341, tier: 'Puppy'},
    {rank: 10, discord_id: 'calcutator', points: 555, tier: 'Puppy'},
    {rank: 11, discord_id: 'thann199', points: 520, tier: 'Puppy'},
    {rank: 12, discord_id: 'samrendra.singh', points: 519, tier: 'Puppy'},
    {rank: 13, discord_id: 'Bert of B', points: 512, tier: 'Puppy'},
    {rank: 14, discord_id: 'hdai58', points: 503, tier: 'Puppy'},
    {rank: 15, discord_id: 'lordcumberlord', points: 458, tier: 'Puppy'},
    {rank: 16, discord_id: 'cheelax', points: 443, tier: 'Puppy'},
    {rank: 17, discord_id: 'apixtwts', points: 417, tier: 'Puppy'},
    {rank: 18, discord_id: 'megumii.eth', points: 410, tier: 'Puppy'},
    {rank: 19, discord_id: 'paulemmanuelng', points: 376, tier: 'Puppy'},
    {rank: 20, discord_id: 'nadai02010', points: 363, tier: 'Puppy'},
    {rank: 21, discord_id: 'femiyoghurt', points: 360, tier: 'Puppy'},
    {rank: 22, discord_id: '0xandee', points: 350, tier: 'Puppy'},
    {rank: 23, discord_id: '.bole007', points: 344, tier: 'Puppy'},
    {rank: 24, discord_id: 'phil26', points: 341, tier: 'Puppy'},
    {rank: 25, discord_id: 'louthing', points: 341, tier: 'Puppy'},
]


export const about_table_data = [
    {tier: 'Puppy', points: 330, reward: '$688'},
    {tier: 'Red Wolf', points: 990, reward: '$1,376'},
    {tier: 'Arctic Wolf', points: 1980, reward: '$2,063'},
    {tier: 'Gray Wolf', points: 3300, reward: '$2,751'},
    {tier: 'Celestial Wolf', points: 4950, reward: '$3,439'},
    {tier: 'Fire Wolf', points: 6930, reward: '$4,127'},
    {tier: 'Shadow Wolf', points: 9240, reward: '$4,815'},
    {tier: 'Ice Wolf', points: 11880, reward: '$5,502'},
    {tier: 'Thunder Wolf', points: 14850, reward: '$6,190'},
    {tier: 'Warg', points: 18150, reward: '$6,878'},
    {tier: 'Werewolf', points: 21780, reward: '$7,566'},
    {tier: 'Fenrir', points: 25740, reward: '$8,253'},
    {tier: 'Dire Wolf', points: 30030, reward: '$8,941'},
]
